name: Build, Test, Package, and Deploy
on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      build_cache_key:
        required: true
        type: string
      is_beta:
        required: true
        type: boolean

    outputs:
      dev_cache_key:
        description: Node development dependencies cache key
        value: ${{ jobs.dependencies.outputs.dev_cache_key}}
      prod_cache_key:
        description: Node production dependencies cache key
        value: ${{ jobs.dependencies.outputs.prod_cache_key}}

jobs:
  dependencies:
    uses: ./.github/workflows/node.dependencies.yml
    secrets: inherit
    with:
      node_version: ${{ inputs.node_version }}

  compile:
    needs: [dependencies]
    uses: ./.github/workflows/compile.yml
    with:
      node_version: ${{ inputs.node_version }}
      build_cache_key: ${{ inputs.build_cache_key }}
      dependencies_cache_key: ${{ needs.dependencies.outputs.dev_cache_key }}

  unittest:
    needs: [compile]
    uses: ./.github/workflows/unit.test.yml
    secrets: inherit
    with:
      node_version: ${{ inputs.node_version }}
      build_cache_key: ${{ inputs.build_cache_key }}

  coverage:
    needs: [unittest]
    uses: ./.github/workflows/coverage.yml
    secrets: inherit

  package:
    needs: [compile]
    uses: ./.github/workflows/package.yml
    with:
      node_version: ${{ inputs.node_version }}
      build_cache_key: ${{ inputs.build_cache_key }}
      build_artifact_folder: 'output'
      build_artifact_name: 'dist'

  deploy:
    needs: [package, coverage]
    uses: ./.github/workflows/deploy.yml
    with:
      build_artifact_name: ${{ needs.package.outputs.build_artifact_name }}
      build_artifact_folder: ${{ needs.package.outputs.build_artifact_folder }}
      node_version: ${{ inputs.node_version }}
      is_beta: ${{ inputs.is_beta }}
    secrets: inherit
