name: Unit Test
on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      build_cache_key:
        required: true
        type: string
      coverage_artifact_folder:
        required: false
        type: string
        default: 'coverage/lcov.info'
      coverage_artifact_name:
        required: false
        type: string
        default: 'code-coverage-report'

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      CLI_TEST: yarn test:ci

    steps:
      - name: Retrieve build cache
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: ./*
          key: ${{ inputs.build_cache_key }}
          fail-on-cache-miss: true

      - name: Setup Node ${{ inputs.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: yarn

      - name: Run tests
        run: ${{ env.CLI_TEST }}

      - name: Upload coverage artifacts
        if: ${{ inputs.coverage_artifact_folder != ''}}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.coverage_artifact_name }}
          path: ${{ inputs.coverage_artifact_folder }}
          retention-days: 1
